### ISSUE TITLE
which file should be load while sample.py

### ISSUE THREAD

**Issue by SeekPoint** [Stardust-/Text-Generate-RNN#3]
ub16c9@ub16c9-gpu:/media/ub16c9/fcd84300-9270-4bbd-896a-5e04e79203b7/ub16_prj/__Gen__/Text-Generate-RNN$ python3.6 sample.py
loading preprocessed files
reading: data/vocab.pkl
words size: 11103
load data done
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1322, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1307, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1409, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.DataLossError: Unable to open table file model/model_loss_4.7890.ckpt-262000.meta: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
	 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]
	 [[Node: save/RestoreV2/_3 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_8_save/RestoreV2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

ub16c9@ub16c9-gpu:/media/ub16c9/fcd84300-9270-4bbd-896a-5e04e79203b7/ub16_prj/__Gen__/Text-Generate-RNN$ tree
.
├── data
│   ├── poetry.txt
│   ├── tang
│   ├── tensor.npy
│   └── vocab.pkl
├── data.py
├── LICENSE
├── model
│   ├── checkpoint
│   ├── model
│   ├── model_loss_1.7149.ckpt-261000.data-00000-of-00001
│   ├── model_loss_1.7149.ckpt-261000.index
│   ├── model_loss_1.7149.ckpt-261000.meta
│   ├── model_loss_2.6208.ckpt-263000.data-00000-of-00001
│   ├── model_loss_2.6208.ckpt-263000.index
│   ├── model_loss_2.6208.ckpt-263000.meta
│   ├── model_loss_3.8258.ckpt-260000.data-00000-of-00001
│   ├── model_loss_3.8258.ckpt-260000.index
│   ├── model_loss_3.8258.ckpt-260000.meta
│   ├── model_loss_4.5588.ckpt-264000.data-00000-of-00001
│   ├── model_loss_4.5588.ckpt-264000.index
│   ├── model_loss_4.5588.ckpt-264000.meta
│   ├── model_loss_4.7890.ckpt-262000.data-00000-of-00001
│   ├── model_loss_4.7890.ckpt-262000.index
│   └── model_loss_4.7890.ckpt-262000.meta
├── net.py

**Comment by stardut** [comment]
Confirm that parameters `num_units` and `num_layer` in `train.py` and `sample.py` are the same

**Comment by SeekPoint** [comment]
i set both :
        num_units = 128
        num_layer = 2
        batch_size = 16
....


ub16c9@ub16c9-gpu:/media/ub16c9/fcd84300-9270-4bbd-896a-5e04e79203b7/ub16_prj/Text-Generate-RNN$ python3.6 sample.py 
loading preprocessed files
reading: data/vocab.pkl
words size: 11103
load data done
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1322, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1307, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1409, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.DataLossError: Unable to open table file model/model_loss_4.7890.ckpt-262000.meta: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
	 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]
	 [[Node: save/RestoreV2/_1 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_6_save/RestoreV2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

**Comment by stardut** [comment]
Are u sure? Maybe you can retrain a model with 1000 step the same parameters to test again?

**Comment by stardut** [comment]
modify samply.py's 33 lines
`saver.restore(self.sess, 'model/model')`
 to 
`saver.restore(self.sess, 'model/model_loss_1.7149.ckpt-261000')`

It's will work.

**Comment by SeekPoint** [comment]
it works
